name: deploy-server
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to Heroku
        env:
          HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_TOKEN }}
          HEROKU_APP_NAME: "our-meeting"
        if: github.ref == 'refs/heads/main' && job.status == 'success'
        run: |
          git subtree push --prefix omserver/ heroku main