name: deploy-server
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: remote add Heroku
        env:
          HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_TOKEN }}
          HEROKU_APP_NAME: "our-meeting"
        run: git remote add heroku-front https://heroku:$HEROKU_API_TOKEN@git.heroku.com/$HEROKU_APP_NAME.git
      - name: Deploy to Heroku
        if: github.ref == 'refs/heads/master' && job.status == 'success'
        run: |
          git push heroku-front `git subtree split --prefix front master`:master --force